# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14fyRq82AgWcn6fZlBNzfoWO_C-X7DLu0
"""

d

def rep_char(c,n) :
  print(c*n)
def draw_line_string(msg1, msg2) :
  nstr = len(msg1) if (len(msg1) > len(msg2)) else len(msg2)
  rep_char('-', nstr + 1)
  print(f'Hello', msg1)
  print(msg2)
  rep_char('_', nstr + 1)
msg1 = input('Input his/her name:')
msg2 = 'Welcom to Seoul.'
draw_line_string(msg1, msg2)

